// ══════════════════════════════════════════════════════════════
// INVOICES.JS — Invoice Generation & Management
// ══════════════════════════════════════════════════════════════

const LS_INVOICES = 'mi_invoices_v2';
let invoiceList = [];

// Always display invoices oldest → newest by date; tie-break on invoice number
function _invByDateAsc(a, b) {
  const da = (a.date || ''), db = (b.date || '');
  if (da !== db) return da < db ? -1 : 1;
  return String(a.id || '').localeCompare(String(b.id || ''), undefined, { numeric: true });
}

function loadInvoices()    { try { return JSON.parse(localStorage.getItem(LS_INVOICES) || '[]'); } catch { return []; } }
function saveInvoiceList() { localStorage.setItem(LS_INVOICES, JSON.stringify(invoiceList)); }
function initInvoices()    { invoiceList = loadInvoices(); }

function generateInvoiceId() {
  let max = 0;
  invoiceList.forEach(inv => {
    const m = String(inv.id || '').match(/INV(\d+)/i);
    if (m) max = Math.max(max, parseInt(m[1]));
  });
  return 'INV' + String(max + 1).padStart(3, '0');
}

// Sum of all qty invoiced against a specific order (per-item orderId links, with
// legacy fallback to the old whole-invoice orderId field)
function getInvoicedQty(orderId) {
  return invoiceList.reduce((sum, inv) => {
    return sum + (inv.items || []).reduce((s, item) => {
      const itemOrder = item.orderId || (inv.orderId || null);
      return s + (itemOrder === orderId ? (item.qty || 0) : 0);
    }, 0);
  }, 0);
}

// How many units of an order are still available to invoice
function orderRemainingToInvoice(o) {
  if (!o) return 0;
  const dispatched = typeof getDispatchedQty === 'function' ? getDispatchedQty(o.id) : (o.qty || 0);
  const base       = dispatched > 0 ? dispatched : (o.qty || 0); // fall back to ordered qty if nothing dispatched yet
  return Math.max(0, base - getInvoicedQty(o.id));
}

// ── Auto-invoice from Delivery Challans ──
// One invoice per challan, whether the challan was entered manually or
// auto-created from the Supervisor Dispatch log. Idempotent via each
// item's challanDc field (the challan's own DC number) — a challan that
// already has an invoice item pointing at it is never re-invoiced.
// Deliberately does NOT touch order status: unlike the manual invoice
// form (which marks an order Delivered on invoicing, an office decision),
// a challan is very often a partial shipment — order completion stays
// driven purely by dispatched-vs-ordered qty (checkOrderFullyDispatched),
// not by whether it's been billed yet.
function _buildInvoiceFromChallan(c) {
  const desc = [c.product || 'Corrugated Box', c.size, c.ply ? c.ply + ' Ply' : '', c.colour].filter(Boolean).join(' · ');
  const qty  = c.qty  || 0;
  const rate = c.rate || 0;
  const amount = qty * rate;
  return {
    id:        generateInvoiceId(),
    party:     c.customer,
    date:      c.date || (typeof todayStr !== 'undefined' ? todayStr : new Date().toISOString().slice(0, 10)),
    orderId:   c.orderId || null,
    items:     [{ desc, qty, rate, amount, orderId: c.orderId || null, challanDc: c.dcNum }],
    subtotal:  amount,
    gstPct:    0,
    gstAmt:    0,
    total:     amount,
    createdAt: new Date().toISOString(),
    autoGenerated: true,
  };
}

// Sweep every challan and invoice any that aren't linked to an invoice yet.
// Skips challans with no rate on file — a ₹0 invoice isn't useful, and
// those are left for manual invoicing once a rate's been agreed.
function autoInvoiceChallans() {
  if (typeof challanList === 'undefined' || !Array.isArray(invoiceList)) return 0;

  const invoicedDcs = new Set();
  invoiceList.forEach(inv => (inv.items || []).forEach(it => { if (it.challanDc) invoicedDcs.add(it.challanDc); }));

  let created = 0;
  challanList.forEach(c => {
    if (!c.dcNum || !c.qty || !c.rate) return;
    if (invoicedDcs.has(c.dcNum)) return;
    const inv = _buildInvoiceFromChallan(c);
    invoiceList.unshift(inv);
    invoicedDcs.add(c.dcNum);
    created++;
    _mirrorInvoice(inv);
  });

  if (created > 0) {
    saveInvoiceList();
    if (typeof renderInvoicingPage === 'function') renderInvoicingPage();
  }
  renderUnratedChallanBanner();
  return created;
}

// Challans that have shipped but have no invoice yet, because they have no
// rate on file to bill at. Shared by the Invoicing page's warning card and
// the dashboard notification banner below.
function _unbilledChallans() {
  if (typeof challanList === 'undefined') return [];
  const invoicedDcs = new Set();
  invoiceList.forEach(inv => (inv.items || []).forEach(it => { if (it.challanDc) invoicedDcs.add(it.challanDc); }));
  return challanList.filter(c => c.dcNum && !invoicedDcs.has(c.dcNum));
}

// Dashboard-level notification for challans stuck without a rate — the
// active, hard-to-miss counterpart to the Invoicing page's warning card.
// "Enter rate & invoice" opens the same fully-editable Create Invoice form
// as every other invoice — party, date, description, qty and rate can all
// be changed there, not just the rate.
function renderUnratedChallanBanner() {
  const banner = document.getElementById('dashboard-rate-banner');
  const badge  = document.getElementById('invoicing-rate-badge');
  const unbilled = _unbilledChallans();

  if (badge) {
    badge.style.display = unbilled.length ? 'inline-block' : 'none';
    badge.textContent = unbilled.length;
  }
  if (!banner) return;
  if (!unbilled.length) { banner.style.display = 'none'; return; }

  banner.style.display = 'block';
  banner.innerHTML = `<div style="font-weight:700;margin-bottom:6px">💰 ${unbilled.length} dispatch${unbilled.length > 1 ? 'es' : ''} waiting on a rate to invoice</div>` +
    unbilled.map(c => `<div style="font-size:12px;margin-top:2px">→ <strong>${c.dcNum}</strong> · ${c.customer} · ${c.product || c.size || '—'} · ${(c.qty || 0).toLocaleString('en-IN')} pcs
      <button class="btn-secondary" style="font-size:10px;padding:2px 8px;margin-left:8px" onclick="resolveChallanInvoice('${c.dcNum}','${c.orderId}')">Enter rate &amp; invoice</button></div>`).join('');
}

// ── Create Invoice Modal ──
// Each item row: { desc, qty, rate, orderId, challanDc } — orderId links the row to an
// order, challanDc (only set via resolveChallanInvoice below) links it to the specific
// challan being billed so it drops off the "waiting on a rate" list once saved.
let _ciItems     = [];
let _ciEditingId = null; // set when editing an existing invoice

// Backward-compat: called from order history rows
function openInvoice(orderId) {
  openCreateInvoiceForm(orderId || null);
}

// Open the invoice form pre-filled for one specific unrated challan (from the
// dashboard banner or the Invoicing page's warning card) — same fully-editable
// form as any other invoice, just tagged so this challan is recognised as
// billed once saved, instead of still showing up as unrated afterwards.
function resolveChallanInvoice(dcNum, orderId) {
  showPage('invoicing');
  openCreateInvoiceForm(orderId);
  if (_ciItems[0]) _ciItems[0].challanDc = dcNum;
}

function openCreateInvoiceForm(orderId) {
  _ciItems = [];
  _ciEditingId = null;
  const overlay = document.getElementById('create-invoice-overlay');
  if (!overlay) return;

  const titleEl = document.querySelector('#create-invoice-overlay .popup-title');
  if (titleEl) titleEl.textContent = '🧾 New Invoice';

  const partyEl = document.getElementById('ci-party');
  if (partyEl) partyEl.value = '';

  const dateEl = document.getElementById('ci-date');
  if (dateEl) dateEl.value = new Date().toISOString().slice(0, 10);

  // Party autocomplete datalist
  const dl = document.getElementById('ci-party-list');
  if (dl && typeof CLIENTS !== 'undefined') {
    dl.innerHTML = CLIENTS.map(c => `<option value="${c.name}">`).join('');
  }

  overlay.style.display = 'flex';

  _ciItems = [{ desc: '', qty: '', rate: '', orderId: null, challanDc: null }];
  if (orderId) {
    const o = typeof orders !== 'undefined' ? orders.find(x => x.id === orderId) : null;
    if (o && partyEl && !partyEl.value) partyEl.value = o.customer || '';
    if (o) _applyOrderToItem(0, o);
  }
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function closeCreateInvoice() {
  const overlay = document.getElementById('create-invoice-overlay');
  if (overlay) overlay.style.display = 'none';
  _hideAllItemDropdowns();
}

function onInvoicePartyChange() {
  // Party changed — order matches may differ; clear any linked rows so nothing stale sticks
  _ciItems.forEach(it => { if (it.orderId) { it.orderId = null; } });
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function _hideAllItemDropdowns() {
  document.querySelectorAll('.ci-item-dd').forEach(dd => { dd.style.display = 'none'; });
}

// Fill item i from an order object
function _applyOrderToItem(i, o) {
  if (!_ciItems[i]) return;
  const remaining = orderRemainingToInvoice(o);
  _ciItems[i].desc    = [o.product || 'Corrugated Box', o.size, o.ply ? o.ply + ' Ply' : '', o.colour].filter(Boolean).join(' · ');
  _ciItems[i].qty     = remaining > 0 ? remaining : '';
  _ciItems[i].rate    = o.rate || '';
  _ciItems[i].orderId = o.id;
}

// ── Per-row product search — fires on every keystroke in a row's product input ──
function onInvoiceItemProductInput(i, val) {
  if (!_ciItems[i]) return;
  _ciItems[i].desc    = val;
  _ciItems[i].orderId = null; // typing unlinks any previous match until re-picked

  const party    = (document.getElementById('ci-party')?.value || '').toLowerCase().trim();
  const product  = (val || '').toLowerCase().trim();
  const dropdown = document.getElementById('ci-item-dd-' + i);
  if (!dropdown) return;

  if (!product) { dropdown.style.display = 'none'; return; }

  const matches = (typeof orders !== 'undefined' ? orders : [])
    .filter(o => o.status !== 'Cancelled')
    .filter(o => !party || o.customer.toLowerCase().includes(party))
    .filter(o => (o.product || '').toLowerCase().includes(product) || (o.size || '').toLowerCase().includes(product))
    .slice(0, 8);

  if (!matches.length) { dropdown.style.display = 'none'; return; }

  dropdown.style.display = 'block';
  dropdown.innerHTML = matches.map(o => {
    const remaining = orderRemainingToInvoice(o);
    const fullyDone = remaining === 0;
    return `
    <div onclick="selectInvoiceItemOrder(${i}, '${o.id}')"
      style="padding:9px 11px;cursor:pointer;border-bottom:1px solid var(--border);${fullyDone ? 'opacity:0.5' : ''}"
      onmouseover="this.style.background='var(--hover-bg,#f5f7fa)'" onmouseout="this.style.background=''">
      <div style="font-size:12px;font-weight:700">${o.customer} — ${o.product || '—'}</div>
      <div style="font-size:11px;color:var(--muted)">${o.id} · ${[o.size, o.ply ? o.ply+' Ply':''].filter(Boolean).join(' · ')} · <strong style="color:${remaining>0?'#B45309':'var(--success)'}">${remaining.toLocaleString('en-IN')} to invoice</strong></div>
    </div>`;
  }).join('');
}

function selectInvoiceItemOrder(i, orderId) {
  const o = typeof orders !== 'undefined' ? orders.find(x => x.id === orderId) : null;
  if (!o) return;

  // Pre-fill party if empty
  const partyEl = document.getElementById('ci-party');
  if (partyEl && !partyEl.value) partyEl.value = o.customer || '';

  _applyOrderToItem(i, o);
  const dd = document.getElementById('ci-item-dd-' + i);
  if (dd) dd.style.display = 'none';
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function renderInvoiceItemRows() {
  const container = document.getElementById('ci-items-table');
  if (!container) return;

  container.innerHTML = `
    <div style="display:grid;grid-template-columns:2fr 80px 90px 88px 24px;gap:6px;font-size:11px;font-weight:700;color:var(--muted);margin-bottom:4px;padding:0 2px">
      <div>Product / Description</div><div>Qty</div><div>Rate (₹)</div><div>Amount</div><div></div>
    </div>` +
    _ciItems.map((item, i) => {
      const linked = item.orderId
        ? `<div style="font-size:10px;color:#15803D;margin-top:3px;display:flex;align-items:center;gap:4px;white-space:nowrap">
             ✅ <strong>${item.orderId}</strong> · deducts + marks Delivered
             <button onclick="_ciItems[${i}].orderId=null;_ciItems[${i}].challanDc=null;renderInvoiceItemRows()" title="Unlink" style="background:none;border:none;cursor:pointer;color:#15803D;font-size:13px;line-height:1">×</button>
           </div>`
        : '';
      return `
    <div style="display:grid;grid-template-columns:2fr 80px 90px 88px 24px;gap:6px;margin-bottom:8px;align-items:start">
      <div style="position:relative">
        <input class="form-input" type="text" placeholder="Type product to find order…" value="${(item.desc || '').replace(/"/g,'&quot;')}"
          autocomplete="off" style="font-size:12px;padding:6px 8px;${item.orderId ? 'border-color:#86EFAC;background:#F0FDF4' : ''}"
          oninput="onInvoiceItemProductInput(${i}, this.value)">
        <div id="ci-item-dd-${i}" class="ci-item-dd" style="display:none;position:absolute;top:100%;left:0;right:0;background:var(--card-bg);border:1px solid var(--border);border-radius:8px;max-height:200px;overflow-y:auto;z-index:${200 - i};box-shadow:0 6px 20px rgba(0,0,0,0.15)"></div>
        ${linked}
      </div>
      <input class="form-input" type="number" placeholder="0" value="${item.qty !== '' ? item.qty : ''}"
        style="font-size:12px;padding:6px 8px" oninput="_ciItems[${i}].qty=+this.value||0;recalcInvoiceTotals()">
      <input class="form-input" type="number" placeholder="0.00" step="0.01" value="${item.rate !== '' ? item.rate : ''}"
        style="font-size:12px;padding:6px 8px" oninput="_ciItems[${i}].rate=+this.value||0;recalcInvoiceTotals()">
      <div style="font-size:12px;font-weight:700;padding:6px 0;text-align:right">₹${(+(item.qty||0) * +(item.rate||0)).toFixed(2)}</div>
      ${_ciItems.length > 1
        ? `<button onclick="removeInvoiceItem(${i})" style="background:none;border:none;cursor:pointer;font-size:18px;color:var(--danger);line-height:1;padding:4px 0">×</button>`
        : '<div></div>'}
    </div>`;
    }).join('');
}

function addInvoiceItemRow() {
  _ciItems.push({ desc: '', qty: '', rate: '', orderId: null, challanDc: null });
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function removeInvoiceItem(i) {
  _ciItems.splice(i, 1);
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function recalcInvoiceTotals() {
  const total = _ciItems.reduce((s, item) => s + +(item.qty || 0) * +(item.rate || 0), 0);
  const fmt2  = n => n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const tot   = document.getElementById('ci-total');
  if (tot) tot.textContent = '₹' + fmt2(total);
}

function _buildInvoiceRecord() {
  const party   = (document.getElementById('ci-party')?.value || '').trim();
  const dateVal = document.getElementById('ci-date')?.value || new Date().toISOString().slice(0, 10);

  const items = _ciItems.filter(item => item.desc && +(item.qty || 0) > 0);

  if (!party)        { alert('Please enter party name.'); return null; }
  if (!items.length) { alert('Please add at least one item with a product name and qty > 0.'); return null; }

  const total = items.reduce((s, i) => s + +(i.qty) * +(i.rate || 0), 0);

  // Primary orderId = first linked row (kept for backward-compat display in list/print)
  const firstLinked = items.find(i => i.orderId);

  return {
    id:        generateInvoiceId(),
    party,
    date:      dateVal,
    orderId:   firstLinked ? firstLinked.orderId : null,
    items:     items.map(i => ({ desc: i.desc, qty: +i.qty, rate: +(i.rate || 0), amount: +i.qty * +(i.rate || 0), orderId: i.orderId || null, challanDc: i.challanDc || null })),
    subtotal:  total,
    gstPct:    0,
    gstAmt:    0,
    total,
    createdAt: new Date().toISOString(),
  };
}

// Persist the built record — creating new or updating the one being edited.
// Returns the saved invoice, or null on validation failure.
function _persistInvoice() {
  const inv = _buildInvoiceRecord();
  if (!inv) return null;

  if (_ciEditingId) {
    const idx = invoiceList.findIndex(x => x.id === _ciEditingId);
    if (idx >= 0) {
      inv.id = _ciEditingId;                       // keep the original number
      inv.createdAt = invoiceList[idx].createdAt;  // keep original timestamp
      invoiceList[idx] = inv;
    } else {
      invoiceList.unshift(inv);
    }
  } else {
    invoiceList.unshift(inv);
  }
  saveInvoiceList();
  _mirrorInvoice(inv);
  _markInvoicedOrdersDelivered(inv);
  return inv;
}

// Push an invoice to its own Invoices sheet (readable columns)
function _mirrorInvoice(inv) {
  if (typeof mirrorToSheet !== 'function') return;
  const orderIds = [...new Set((inv.items || []).map(i => i.orderId).filter(Boolean))].join(', ');
  const itemsTxt = (inv.items || []).map(i => `${i.desc} x${i.qty} @${i.rate}`).join('; ');
  const qty      = (inv.items || []).reduce((s, i) => s + (i.qty || 0), 0);
  mirrorToSheet('saveInvoice', {
    id: inv.id, date: inv.date, party: inv.party, orderIds,
    items: itemsTxt, qty, total: inv.total, createdAt: inv.createdAt || '',
  });
}

// Any order linked from this invoice's items is considered fully billed → Delivered.
function _markInvoicedOrdersDelivered(inv) {
  if (typeof orders === 'undefined') return;
  const orderIds = [...new Set((inv.items || []).map(i => i.orderId).filter(Boolean))];
  orderIds.forEach(oid => {
    const o = orders.find(x => x.id === oid);
    if (o && o.status !== 'Delivered' && o.status !== 'Cancelled') {
      markOrderDelivered(o);
    }
  });
}

// Flip an order to Delivered — optimistic local update + push to the sheet.
function markOrderDelivered(o) {
  o.status = 'Delivered';
  if (typeof recordDeliveredOrder === 'function') recordDeliveredOrder(o);
  if (typeof recordDeliveryLead   === 'function') recordDeliveryLead(o);
  try {
    const d   = o.date ? new Date(o.date) : new Date();
    const fmt = `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`;
    const od  = o.orderDate ? new Date(o.orderDate) : d;
    const fod = `${String(od.getDate()).padStart(2,'0')}/${String(od.getMonth()+1).padStart(2,'0')}/${od.getFullYear()}`;
    fetch(APPS_SCRIPT_URL, {
      method: 'POST', mode: 'no-cors', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'update', rowIndex: o.rowIndex, id: o.id, customer: o.customer,
        product: o.product, size: o.size, ply: o.ply, colour: o.colour, weight: o.weight,
        qty: o.qty, rate: o.rate, date: fmt, orderDate: fod, status: 'Delivered',
        priority: o.priority, reelSize: o.reelSize, reservedKg: o.reservedKg || 0, remarks: '',
      }),
    }).catch(() => {});
  } catch (e) { /* non-fatal */ }
}

function saveInvoiceOnly() {
  const inv = _persistInvoice();
  if (!inv) return;
  const wasEditing = !!_ciEditingId;
  closeCreateInvoice();
  renderInvoicingPage();
  renderUnratedChallanBanner();
  if (typeof renderOrders === 'function') renderOrders();
  if (typeof updateDashboardOrders === 'function') updateDashboardOrders();
  alert(`✅ ${inv.id} ${wasEditing ? 'updated' : 'saved'}!`);
}

function saveAndPrintInvoice() {
  const inv = _persistInvoice();
  if (!inv) return;
  closeCreateInvoice();
  renderInvoicingPage();
  renderUnratedChallanBanner();
  if (typeof renderOrders === 'function') renderOrders();
  if (typeof updateDashboardOrders === 'function') updateDashboardOrders();
  _populateInvoiceOverlay(inv);
}

// Re-open the create form pre-filled to edit an existing invoice
function editInvoice(invId) {
  const inv = invoiceList.find(i => i.id === invId);
  if (!inv) return;
  const overlay = document.getElementById('create-invoice-overlay');
  if (!overlay) return;

  _ciEditingId = invId;
  _ciItems = (inv.items || []).map(i => ({ desc: i.desc, qty: i.qty, rate: i.rate, orderId: i.orderId || null, challanDc: i.challanDc || null }));
  if (!_ciItems.length) _ciItems = [{ desc: '', qty: '', rate: '', orderId: null, challanDc: null }];

  const titleEl = document.querySelector('#create-invoice-overlay .popup-title');
  if (titleEl) titleEl.textContent = `✏️ Edit Invoice ${inv.id}`;

  const partyEl = document.getElementById('ci-party');
  if (partyEl) partyEl.value = inv.party || '';
  const dateEl = document.getElementById('ci-date');
  if (dateEl) dateEl.value = inv.date || new Date().toISOString().slice(0, 10);

  const dl = document.getElementById('ci-party-list');
  if (dl && typeof CLIENTS !== 'undefined') dl.innerHTML = CLIENTS.map(c => `<option value="${c.name}">`).join('');

  overlay.style.display = 'flex';
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function _populateInvoiceOverlay(inv) {
  const ordObj = inv.orderId && typeof orders !== 'undefined' ? orders.find(o => o.id === inv.orderId) : null;
  const client = inv.party && typeof CLIENTS !== 'undefined'
    ? (CLIENTS.find(c => c.name.toLowerCase() === inv.party.toLowerCase()) || {})
    : {};
  const fmt2   = n => n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const dateStr = (() => {
    try { return new Date(inv.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }); }
    catch { return inv.date; }
  })();

  document.getElementById('inv-number').textContent          = inv.id;
  document.getElementById('inv-date').textContent            = dateStr;
  document.getElementById('inv-order-id').textContent        = inv.orderId || '—';
  document.getElementById('inv-delivery-date').textContent   = ordObj ? formatDate(ordObj.date) : '—';
  document.getElementById('inv-customer-name').textContent   = inv.party;
  document.getElementById('inv-customer-contact').textContent = client.contact || '';
  document.getElementById('inv-customer-city').textContent   = client.city    || '';
  document.getElementById('inv-customer-phone').textContent  = client.phone   ? '📞 ' + client.phone : '';

  document.getElementById('inv-items').innerHTML = inv.items.map(item => `
    <tr style="border-bottom:1px solid #e5e7eb">
      <td style="padding:12px;font-size:13px">${item.desc}</td>
      <td style="padding:12px;text-align:center;font-size:13px">${item.qty.toLocaleString('en-IN')} pcs</td>
      <td style="padding:12px;text-align:right;font-size:13px">₹${item.rate.toFixed(2)}</td>
      <td style="padding:12px;text-align:right;font-size:13px;font-weight:600">₹${fmt2(item.amount)}</td>
    </tr>`).join('');

  const hasGst = (inv.gstPct || 0) > 0;
  document.getElementById('inv-subtotal').textContent = '₹' + fmt2(inv.subtotal);
  const gstRow      = document.getElementById('inv-gst-row');
  const subtotalRow = document.getElementById('inv-subtotal-row');
  const docTitle    = document.getElementById('inv-doc-title');
  if (gstRow)      gstRow.style.display      = hasGst ? '' : 'none';
  if (subtotalRow) subtotalRow.style.display = hasGst ? '' : 'none'; // no GST → subtotal == total, hide the duplicate line
  if (docTitle)    docTitle.textContent      = hasGst ? 'TAX INVOICE' : 'INVOICE';
  if (hasGst) {
    const gstLabelEl = document.getElementById('inv-gst-label');
    if (gstLabelEl) gstLabelEl.textContent = `GST @ ${inv.gstPct}%`;
    document.getElementById('inv-gst').textContent = '₹' + fmt2(inv.gstAmt);
  }
  document.getElementById('inv-total').textContent = '₹' + fmt2(inv.total);
  document.getElementById('inv-amount-words').textContent = amountToWords(Math.round(inv.total));

  document.getElementById('invoice-overlay').style.display = 'flex';
}

function reprintInvoice(invId) {
  const inv = invoiceList.find(i => i.id === invId);
  if (inv) _populateInvoiceOverlay(inv);
}

function deleteInvoice(invId) {
  if (!confirm(`Delete invoice ${invId}? This cannot be undone.`)) return;
  invoiceList = invoiceList.filter(inv => inv.id !== invId);
  saveInvoiceList();
  if (typeof mirrorToSheet === 'function') mirrorToSheet('deleteInvoice', { id: invId });
  renderInvoicingPage();
  renderUnratedChallanBanner();
  if (typeof renderOrders === 'function') renderOrders();
}

function closeInvoice() {
  document.getElementById('invoice-overlay').style.display = 'none';
}

// Close per-row product dropdowns on outside click
document.addEventListener('click', e => {
  const table = document.getElementById('ci-items-table');
  if (table && !table.contains(e.target)) _hideAllItemDropdowns();
});

// ── Print Invoice (new window) ──
function printInvoice() {
  const content = document.getElementById('invoice-printable').innerHTML;
  const win = window.open('', '_blank');
  win.document.write(`
    <!DOCTYPE html><html><head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: 'Inter', Arial, sans-serif; padding: 40px; font-size: 13px; color: #111; }
      table { width: 100%; border-collapse: collapse; }
      th, td { border: 1px solid #e5e7eb; }
    </style>
    </head><body>${content}</body></html>
  `);
  win.document.close();
  win.focus();
  win.print();
}

// ── Month filter — defaults to the current month (or the most recent month
// that actually has invoices, if this one doesn't) the first time the page
// renders; stays wherever the user leaves it after that. ──
let _invMonthFilter = null;

function _invMonthKey(dateStr)  { return (dateStr || '').slice(0, 7); } // 'YYYY-MM'
function _invMonthLabel(key) {
  const [y, m] = key.split('-').map(Number);
  return new Date(y, m - 1, 1).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
}

function setInvoiceMonthFilter(key) {
  _invMonthFilter = key;
  renderInvoicingPage();
}

// ── Invoicing Page ──
function renderInvoicingPage() {
  const el = document.getElementById('invoicing-page-content');
  if (!el) return;

  const fmt2 = n => n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const allMonths = [...new Set(invoiceList.map(inv => _invMonthKey(inv.date)).filter(Boolean))].sort().reverse();
  if (_invMonthFilter === null) {
    const curMonth = todayStr.slice(0, 7);
    _invMonthFilter = allMonths.includes(curMonth) ? curMonth : (allMonths[0] || 'all');
  }
  const filtered = _invMonthFilter === 'all' ? invoiceList : invoiceList.filter(inv => _invMonthKey(inv.date) === _invMonthFilter);

  const totalInvoiced = filtered.reduce((s, inv) => s + inv.total, 0);
  const unbilled = _unbilledChallans();

  const monthSelect = `
    <select class="form-select" style="font-size:13px;width:auto;padding:8px 10px" onchange="setInvoiceMonthFilter(this.value)">
      <option value="all" ${_invMonthFilter === 'all' ? 'selected' : ''}>All Months</option>
      ${allMonths.map(m => `<option value="${m}" ${m === _invMonthFilter ? 'selected' : ''}>${_invMonthLabel(m)}</option>`).join('')}
    </select>`;

  el.innerHTML = `
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;flex-wrap:wrap;gap:8px">
      <div style="display:flex;gap:12px;flex-wrap:wrap;align-items:center">
        ${monthSelect}
        <div class="stat-card good" style="padding:10px 16px;min-width:140px">
          <div class="stat-label">Total Invoiced${_invMonthFilter !== 'all' ? ' — ' + _invMonthLabel(_invMonthFilter) : ''}</div>
          <div class="stat-value" style="color:var(--success);font-size:18px">₹${fmt2(totalInvoiced)}</div>
        </div>
        <div class="stat-card info" style="padding:10px 16px;min-width:100px">
          <div class="stat-label">Invoices</div>
          <div class="stat-value">${filtered.length}</div>
        </div>
      </div>
      <button class="btn-primary" onclick="openCreateInvoiceForm(null)" style="font-size:13px">+ New Invoice</button>
    </div>

    ${unbilled.length ? `
    <div class="card" style="margin-bottom:16px;border-color:#FBBF24">
      <div class="card-body" style="padding:12px 16px">
        <div style="font-size:12px;font-weight:700;color:#B45309;margin-bottom:6px">⚠️ ${unbilled.length} delivery challan${unbilled.length > 1 ? 's' : ''} not yet invoiced — no rate on file</div>
        <div style="font-size:11px;color:var(--muted);margin-bottom:8px">These dispatched automatically but have no rate to bill from. Add a rate on the order (or the product master) and they'll invoice on the next dispatch refresh — or invoice them manually now.</div>
        <div style="display:flex;flex-direction:column;gap:4px">
          ${unbilled.map(c => `<div style="font-size:12px;display:flex;gap:10px;flex-wrap:wrap">
            <span style="font-family:monospace;color:var(--navy);font-weight:700">${c.dcNum}</span>
            <span>${c.customer}</span>
            <span style="color:var(--muted)">${c.product || c.size || '—'}</span>
            <span style="color:var(--muted)">${(c.qty || 0).toLocaleString('en-IN')} pcs</span>
            <button class="btn-secondary" style="font-size:10px;padding:2px 8px;margin-left:auto" onclick="resolveChallanInvoice('${c.dcNum}','${c.orderId}')">+ Invoice manually</button>
          </div>`).join('')}
        </div>
      </div>
    </div>` : ''}

    ${filtered.length === 0
      ? `<div class="empty-state">${invoiceList.length === 0 ? 'No invoices yet. Click "+ New Invoice" to create one.' : `No invoices in ${_invMonthFilter === 'all' ? 'range' : _invMonthLabel(_invMonthFilter)}.`}</div>`
      : `<div class="card">
          <div class="card-body" style="padding:0">
            <div class="orders-table">
              <div class="table-header" style="grid-template-columns:90px 100px 1.4fr 1fr 70px 100px 130px">
                <div>Invoice #</div><div>Date</div><div>Party</div><div>Order</div><div>Qty</div><div>Total</div><div>Actions</div>
              </div>
              ${filtered.slice().sort(_invByDateAsc).map(inv => {
                const qty = (inv.items || []).reduce((s, i) => s + (i.qty || 0), 0);
                const dateDisp = (() => { try { return new Date(inv.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }); } catch { return inv.date; } })();
                const orderIds = [...new Set((inv.items || []).map(i => i.orderId).filter(Boolean))];
                const orderLbl = orderIds.length ? orderIds.join(', ') : (inv.orderId || '—');
                return `
                <div class="table-row" style="grid-template-columns:90px 100px 1.4fr 1fr 70px 100px 130px">
                  <div style="font-family:monospace;font-size:12px;color:var(--navy);font-weight:700">${inv.id}${inv.autoGenerated ? ` <span style="font-family:inherit;font-size:9px;font-weight:700;color:var(--success,#27AE60);background:#F0FDF4;padding:1px 5px;border-radius:3px;vertical-align:middle" title="Auto-generated from a Delivery Challan">AUTO</span>` : ''}</div>
                  <div style="font-size:12px">${dateDisp}</div>
                  <div style="font-size:12px;font-weight:600">${inv.party}</div>
                  <div style="font-size:11px;font-family:monospace;color:var(--muted)">${orderLbl}</div>
                  <div style="font-size:12px">${qty.toLocaleString('en-IN')}</div>
                  <div style="font-size:12px;font-weight:700;color:var(--navy)">₹${fmt2(inv.total)}</div>
                  <div style="display:flex;gap:5px;align-items:center">
                    <button class="btn-secondary" style="font-size:10px;padding:3px 7px" onclick="editInvoice('${inv.id}')" title="Edit">✏️</button>
                    <button class="btn-secondary" style="font-size:10px;padding:3px 7px" onclick="reprintInvoice('${inv.id}')" title="Print">🖨</button>
                    <button style="background:none;border:none;cursor:pointer;font-size:15px;color:var(--danger)" onclick="deleteInvoice('${inv.id}')" title="Delete">🗑</button>
                  </div>
                </div>`;
              }).join('')}
            </div>
          </div>
        </div>`
    }
  `;
}

// ── Number to Words (Indian format) ──
function amountToWords(amount) {
  if (amount === null || amount === undefined || isNaN(amount)) return '';
  if (amount === 0) return 'Rupees Zero Only';
  const ones = ['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine',
    'Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'];
  const tens = ['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];
  function convert(n) {
    if (n < 20) return ones[n];
    if (n < 100) return tens[Math.floor(n/10)] + (n%10 ? ' ' + ones[n%10] : '');
    if (n < 1000) return ones[Math.floor(n/100)] + ' Hundred' + (n%100 ? ' ' + convert(n%100) : '');
    if (n < 100000) return convert(Math.floor(n/1000)) + ' Thousand' + (n%1000 ? ' ' + convert(n%1000) : '');
    if (n < 10000000) return convert(Math.floor(n/100000)) + ' Lakh' + (n%100000 ? ' ' + convert(n%100000) : '');
    return convert(Math.floor(n/10000000)) + ' Crore' + (n%10000000 ? ' ' + convert(n%10000000) : '');
  }
  return 'Rupees ' + convert(amount) + ' Only';
}
