// ══════════════════════════════════════════════════════════════
// INVOICES.JS — Invoice Generation & Management
// ══════════════════════════════════════════════════════════════

const LS_INVOICES = 'mi_invoices_v2';
let invoiceList = [];

// Oldest → newest by date first (so the list reads chronologically); within
// the same date, grouped by party so multiple invoices billed to the same
// customer that day sit together instead of interleaved by whoever else
// was billed that day; tie-break on invoice number.
function _invByDateThenParty(a, b) {
  const da = (a.date || ''), db = (b.date || '');
  if (da !== db) return da < db ? -1 : 1;
  const pa = (a.party || '').toLowerCase(), pb = (b.party || '').toLowerCase();
  if (pa !== pb) return pa < pb ? -1 : 1;
  return String(a.id || '').localeCompare(String(b.id || ''), undefined, { numeric: true });
}

function loadInvoices()    { try { return JSON.parse(localStorage.getItem(LS_INVOICES) || '[]'); } catch { return []; } }
function saveInvoiceList() { localStorage.setItem(LS_INVOICES, JSON.stringify(invoiceList)); }
function initInvoices()    { invoiceList = loadInvoices(); }

function generateInvoiceId() {
  let max = 0;
  invoiceList.forEach(inv => {
    const m = String(inv.id || '').match(/INV(\d+)/i);
    if (m) max = Math.max(max, parseInt(m[1]));
  });
  return 'INV' + String(max + 1).padStart(3, '0');
}

// Sum of all qty invoiced against a specific order (per-item orderId links, with
// legacy fallback to the old whole-invoice orderId field)
function getInvoicedQty(orderId) {
  return invoiceList.reduce((sum, inv) => {
    return sum + (inv.items || []).reduce((s, item) => {
      const itemOrder = item.orderId || (inv.orderId || null);
      return s + (itemOrder === orderId ? (item.qty || 0) : 0);
    }, 0);
  }, 0);
}

// How many units of an order are still available to invoice
function orderRemainingToInvoice(o) {
  if (!o) return 0;
  const dispatched = typeof getDispatchedQty === 'function' ? getDispatchedQty(o.id) : (o.qty || 0);
  const base       = dispatched > 0 ? dispatched : (o.qty || 0); // fall back to ordered qty if nothing dispatched yet
  return Math.max(0, base - getInvoicedQty(o.id));
}

// ── Auto-invoice from Delivery Challans ──
// One invoice per challan, whether the challan was entered manually or
// auto-created from the Supervisor Dispatch log. Idempotent via each
// item's challanDc field (the challan's own DC number) — a challan that
// already has an invoice item pointing at it is never re-invoiced.
// Deliberately does NOT touch order status: unlike the manual invoice
// form (which marks an order Delivered on invoicing, an office decision),
// a challan is very often a partial shipment — order completion stays
// driven purely by dispatched-vs-ordered qty (checkOrderFullyDispatched),
// not by whether it's been billed yet.
function _buildInvoiceFromChallan(c) {
  const desc = [c.product || 'Corrugated Box', c.size, c.ply ? c.ply + ' Ply' : '', c.colour].filter(Boolean).join(' · ');
  const qty  = c.qty  || 0;
  const rate = c.rate || 0;
  const amount   = qty * rate;
  const total    = Math.round(amount);
  const roundOff = total - amount;
  return {
    id:        generateInvoiceId(),
    party:     c.customer,
    date:      c.date || (typeof todayStr !== 'undefined' ? todayStr : new Date().toISOString().slice(0, 10)),
    orderId:   c.orderId || null,
    items:     [{ desc, qty, rate, amount, orderId: c.orderId || null, challanDc: c.dcNum }],
    subtotal:  amount,
    gstPct:    0,
    gstAmt:    0,
    roundOff,
    total,
    createdAt: new Date().toISOString(),
    autoGenerated: true,
  };
}

// Sweep every challan and invoice any that aren't linked to an invoice yet.
// Skips challans with no rate on file — a ₹0 invoice isn't useful, and
// those are left for manual invoicing once a rate's been agreed.
function autoInvoiceChallans() {
  if (typeof challanList === 'undefined' || !Array.isArray(invoiceList)) return 0;

  const invoicedDcs = new Set();
  invoiceList.forEach(inv => (inv.items || []).forEach(it => { if (it.challanDc) invoicedDcs.add(it.challanDc); }));

  let created = 0;
  let ratesBackfilled = false;
  challanList.forEach(c => {
    if (!c.dcNum || !c.qty) return;
    if (invoicedDcs.has(c.dcNum)) return;
    // A challan's rate is stamped from the order at creation time — if the
    // order was dispatched before a rate was agreed, the challan was stuck
    // at 0 forever even after the order got a real rate later. Pick that up
    // now instead of leaving it silently unbilled.
    if (!c.rate) {
      const o = typeof orders !== 'undefined' ? orders.find(x => x.id === c.orderId) : null;
      if (o && o.rate) { c.rate = o.rate; ratesBackfilled = true; }
    }
    if (!c.rate) return;
    const inv = _buildInvoiceFromChallan(c);
    invoiceList.unshift(inv);
    invoicedDcs.add(c.dcNum);
    created++;
    _mirrorInvoice(inv);
    if (typeof logOrderEvent === 'function' && c.orderId) logOrderEvent(c.orderId, 'Invoiced', `${inv.id} · ₹${inv.total.toLocaleString('en-IN')} (auto, from ${c.dcNum})`);
  });

  if (ratesBackfilled && typeof saveChallans === 'function') saveChallans();
  if (created > 0) {
    saveInvoiceList();
    if (typeof renderInvoicingPage === 'function') renderInvoicingPage();
  }
  renderUnratedChallanBanner();
  return created;
}

// Challans that have shipped but have no invoice yet, because they have no
// rate on file to bill at. Shared by the Invoicing page's warning card and
// the dashboard notification banner below.
function _unbilledChallans() {
  if (typeof challanList === 'undefined') return [];
  const invoicedDcs = new Set();
  invoiceList.forEach(inv => (inv.items || []).forEach(it => { if (it.challanDc) invoicedDcs.add(it.challanDc); }));
  return challanList.filter(c => c.dcNum && !invoicedDcs.has(c.dcNum));
}

// Dashboard-level notification for challans stuck without a rate — the
// active, hard-to-miss counterpart to the Invoicing page's warning card.
// "Enter rate & invoice" opens the same fully-editable Create Invoice form
// as every other invoice — party, date, description, qty and rate can all
// be changed there, not just the rate.
function renderUnratedChallanBanner() {
  const banner = document.getElementById('dashboard-rate-banner');
  const badge  = document.getElementById('invoicing-rate-badge');
  const unbilled = _unbilledChallans();

  if (badge) {
    badge.style.display = unbilled.length ? 'inline-block' : 'none';
    badge.textContent = unbilled.length;
  }
  if (!banner) return;
  if (!unbilled.length) { banner.style.display = 'none'; return; }

  banner.style.display = 'block';
  banner.innerHTML = `<div style="font-weight:700;margin-bottom:6px">💰 ${unbilled.length} dispatch${unbilled.length > 1 ? 'es' : ''} waiting on a rate to invoice</div>` +
    unbilled.map(c => `<div style="font-size:12px;margin-top:2px">→ <strong>${c.dcNum}</strong> · ${c.customer} · ${c.product || c.size || '—'} · ${(c.qty || 0).toLocaleString('en-IN')} pcs
      <button class="btn-secondary" style="font-size:10px;padding:2px 8px;margin-left:8px" onclick="resolveChallanInvoice('${c.dcNum}','${c.orderId}')">Enter rate &amp; invoice</button></div>`).join('');
}

// ── Create Invoice Modal ──
// Each item row: { desc, qty, rate, orderId, challanDc } — orderId links the row to an
// order, challanDc (only set via resolveChallanInvoice below) links it to the specific
// challan being billed so it drops off the "waiting on a rate" list once saved.
let _ciItems     = [];
let _ciEditingId = null; // set when editing an existing invoice

// Backward-compat: called from order history rows
function openInvoice(orderId) {
  openCreateInvoiceForm(orderId || null);
}

// Open the invoice form pre-filled for one specific unrated challan (from the
// dashboard banner, the Invoicing page's warning card, or a Supervisor Log
// row) — same fully-editable form as any other invoice, just tagged so this
// challan is recognised as billed once saved. The form is a fixed overlay
// that renders on top of whatever page is open, so this deliberately does
// NOT navigate — opening it from Supervisor Log (or the Dashboard) should
// leave you right back where you were once it closes, not jump you away.
function resolveChallanInvoice(dcNum, orderId) {
  openCreateInvoiceForm(orderId);
  if (_ciItems[0]) _ciItems[0].challanDc = dcNum;
}

function openCreateInvoiceForm(orderId) {
  _ciItems = [];
  _ciEditingId = null;
  const overlay = document.getElementById('create-invoice-overlay');
  if (!overlay) return;

  const titleEl = document.querySelector('#create-invoice-overlay .popup-title');
  if (titleEl) titleEl.textContent = '🧾 New Invoice';

  const partyEl = document.getElementById('ci-party');
  if (partyEl) partyEl.value = '';

  const dateEl = document.getElementById('ci-date');
  if (dateEl) dateEl.value = new Date().toISOString().slice(0, 10);

  // Party autocomplete datalist
  const dl = document.getElementById('ci-party-list');
  if (dl && typeof CLIENTS !== 'undefined') {
    dl.innerHTML = CLIENTS.map(c => `<option value="${c.name}">`).join('');
  }

  overlay.style.display = 'flex';

  _ciItems = [{ desc: '', qty: '', rate: '', orderId: null, challanDc: null }];
  if (orderId) {
    const o = typeof orders !== 'undefined' ? orders.find(x => x.id === orderId) : null;
    if (o && partyEl && !partyEl.value) partyEl.value = o.customer || '';
    if (o) _applyOrderToItem(0, o);
  }
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

// Open the invoice form pre-filled from raw dispatch info (party/product/qty)
// with no order attached at all — for goods that went out with nothing on
// the Orders page to link back to (e.g. a Supervisor Log dispatch entry that
// never matched any order). Same fully-editable form as any other invoice;
// the item's orderId simply stays null, which every other part of invoicing
// already treats as a valid, unlinked line item.
// svTs (optional): the originating Supervisor Log entry's own timestamp —
// stamped onto the item so that entry can recognise it's already been
// invoiced directly (no challan involved) and stop offering to invoice it
// again, the same way a challan's svTs already prevents a double-challan.
function openDirectInvoiceForm(party, desc, qty, date, svTs) {
  openCreateInvoiceForm(null);
  const partyEl = document.getElementById('ci-party');
  if (partyEl) partyEl.value = party || '';
  const dateEl = document.getElementById('ci-date');
  if (dateEl && date) dateEl.value = date;
  _ciItems = [{ desc: desc || '', qty: qty || '', rate: '', orderId: null, challanDc: null, svTs: svTs || null }];
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function closeCreateInvoice() {
  const overlay = document.getElementById('create-invoice-overlay');
  if (overlay) overlay.style.display = 'none';
  _hideAllItemDropdowns();
}

function onInvoicePartyChange() {
  // Party changed — order matches may differ; clear any linked rows so nothing stale sticks
  _ciItems.forEach(it => { if (it.orderId) { it.orderId = null; } });
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function _hideAllItemDropdowns() {
  document.querySelectorAll('.ci-item-dd').forEach(dd => { dd.style.display = 'none'; });
}

// Fill item i from an order object
function _applyOrderToItem(i, o) {
  if (!_ciItems[i]) return;
  const remaining = orderRemainingToInvoice(o);
  _ciItems[i].desc    = [o.product || 'Corrugated Box', o.size, o.ply ? o.ply + ' Ply' : '', o.colour].filter(Boolean).join(' · ');
  _ciItems[i].qty     = remaining > 0 ? remaining : '';
  _ciItems[i].rate    = o.rate || '';
  _ciItems[i].orderId = o.id;
}

// Loose match for box-size text — "16.5x9.5x14", "16.5×9.5×14" and
// "16.5*9.5*14" should all be treated as the same string, since the sheet
// and a person typing it use different separators.
function _normDims(s) {
  return (s || '').toLowerCase().replace(/[×x*]/g, ' ').replace(/\s+/g, ' ').trim();
}

// ── Per-row product search ──
// Fires on every keystroke AND on focus (with whatever text is already
// there, including none) — so clicking into an empty field for a party
// that's already filled in shows that party's open orders and product
// catalog immediately, not just once you start typing.
function onInvoiceItemProductInput(i, val) {
  if (!_ciItems[i]) return;
  _ciItems[i].desc    = val;
  _ciItems[i].orderId = null; // typing unlinks any previous match until re-picked
  _updateItemDropdown(i, val);
}

function onInvoiceItemProductFocus(i) {
  if (!_ciItems[i]) return;
  _updateItemDropdown(i, _ciItems[i].desc || '');
}

function _findClientForParty(party) {
  if (typeof CLIENTS === 'undefined' || !party) return null;
  const p = party.toLowerCase().trim();
  return CLIENTS.find(c => c.name.toLowerCase() === p) ||
         CLIENTS.find(c => c.name.toLowerCase().includes(p) || p.includes(c.name.toLowerCase())) ||
         null;
}

function _updateItemDropdown(i, val) {
  const party     = (document.getElementById('ci-party')?.value || '').trim();
  const partyLow  = party.toLowerCase();
  const product   = (val || '').toLowerCase().trim();
  const productD  = _normDims(val);
  const dropdown  = document.getElementById('ci-item-dd-' + i);
  if (!dropdown) return;

  const matchesText = o => !product || (o.product || '').toLowerCase().includes(product) ||
    _normDims(o.size).includes(productD) ||
    o.id.toLowerCase().includes(product);

  const notCancelled = (typeof orders !== 'undefined' ? orders : []).filter(o => o.status !== 'Cancelled');

  // Party + text match first; if that comes up empty while actively
  // searching (e.g. the party field doesn't exactly match how this order's
  // customer is spelled in the sheet), fall back to matching on the typed
  // text alone across every customer — a product/size/order-ID match
  // should never come up blank just because the party string didn't line up.
  let orderMatches = notCancelled
    .filter(o => !partyLow || o.customer.toLowerCase().includes(partyLow))
    .filter(matchesText);
  if (!orderMatches.length && partyLow && product) orderMatches = notCancelled.filter(matchesText);
  orderMatches = orderMatches.slice(0, 6);

  // The party's full product catalog (Clients page) — every product they've
  // ever ordered, not just ones with an order open right now, plus a way to
  // add one on the spot if it isn't there yet.
  const client = _findClientForParty(party);
  const productMatches = client
    ? client.products
        .map((p, pi) => ({ p, pi }))
        .filter(({ p }) => !product || p.name.toLowerCase().includes(product) || _normDims(p.size).includes(productD))
        .slice(0, 8)
    : [];

  if (!orderMatches.length && !productMatches.length && !client) { dropdown.style.display = 'none'; return; }

  const sectionLabel = txt => `<div style="padding:6px 11px;font-size:10px;font-weight:700;color:var(--muted);text-transform:uppercase;letter-spacing:0.4px;background:var(--bg)">${txt}</div>`;

  let html = '';
  if (orderMatches.length) {
    html += sectionLabel('Open Orders');
    html += orderMatches.map(o => {
      const remaining = orderRemainingToInvoice(o);
      const fullyDone = remaining === 0;
      return `
      <div onclick="selectInvoiceItemOrder(${i}, '${o.id}')"
        style="padding:9px 11px;cursor:pointer;border-bottom:1px solid var(--border);${fullyDone ? 'opacity:0.5' : ''}"
        onmouseover="this.style.background='var(--hover-bg,#f5f7fa)'" onmouseout="this.style.background=''">
        <div style="font-size:12px;font-weight:700">${o.customer} — ${o.product || '—'}</div>
        <div style="font-size:11px;color:var(--muted)">${o.id} · ${[o.size, o.ply ? o.ply+' Ply':''].filter(Boolean).join(' · ')} · <strong style="color:${remaining>0?'#B45309':'var(--success)'}">${remaining.toLocaleString('en-IN')} to invoice</strong></div>
      </div>`;
    }).join('');
  }
  if (productMatches.length) {
    html += sectionLabel(`${client.name}'s Products`);
    html += productMatches.map(({ p, pi }) => `
      <div onclick="selectInvoiceItemProduct(${i}, '${escStr(client.name)}', ${pi})"
        style="padding:9px 11px;cursor:pointer;border-bottom:1px solid var(--border)"
        onmouseover="this.style.background='var(--hover-bg,#f5f7fa)'" onmouseout="this.style.background=''">
        <div style="font-size:12px;font-weight:700">${p.name}</div>
        <div style="font-size:11px;color:var(--muted)">${[p.size, p.ply ? p.ply+' Ply':''].filter(Boolean).join(' · ')}${p.rate ? ' · ₹'+p.rate+'/pc on file' : ' · no rate on file — enter one after picking'}</div>
      </div>`).join('');
  }
  if (client) {
    html += `
      <div onclick="_addProductForInvoiceItem(${i}, '${escStr(client.name)}')"
        style="padding:9px 11px;cursor:pointer;color:var(--blue);font-weight:600;font-size:12px"
        onmouseover="this.style.background='var(--hover-bg,#f5f7fa)'" onmouseout="this.style.background=''">
        + Add Product for ${client.name}
      </div>`;
  }

  dropdown.innerHTML = html;
  dropdown.style.display = 'block';
}

// Fill item i from a client's existing product-master entry — no order
// behind it, so qty/orderId are left alone (rate fills in if the product
// has one on file).
function selectInvoiceItemProduct(i, clientName, pi) {
  const client = _findClientForParty(clientName);
  const p = client && client.products[pi];
  if (!p || !_ciItems[i]) return;
  _ciItems[i].desc      = [p.name, p.size, p.ply ? p.ply + ' Ply' : '', p.colour].filter(Boolean).join(' · ');
  _ciItems[i].rate      = p.rate || _ciItems[i].rate || '';
  _ciItems[i].orderId   = null;
  _ciItems[i].challanDc = null;
  const dd = document.getElementById('ci-item-dd-' + i);
  if (dd) dd.style.display = 'none';
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

// Add a brand-new product to this party's master from right inside the
// invoice form, then drop straight back in with it filled into this item.
function _addProductForInvoiceItem(i, clientName) {
  const ci = typeof CLIENTS !== 'undefined' ? CLIENTS.findIndex(c => c.name === clientName) : -1;
  if (ci < 0 || typeof openProductModal !== 'function') return;
  _hideAllItemDropdowns();
  openProductModal(ci, -1, product => {
    if (!_ciItems[i]) return;
    _ciItems[i].desc      = [product.name, product.size, product.ply ? product.ply + ' Ply' : '', product.colour].filter(Boolean).join(' · ');
    _ciItems[i].rate      = product.rate || '';
    _ciItems[i].orderId   = null;
    _ciItems[i].challanDc = null;
    renderInvoiceItemRows();
    recalcInvoiceTotals();
  });
}

function selectInvoiceItemOrder(i, orderId) {
  const o = typeof orders !== 'undefined' ? orders.find(x => x.id === orderId) : null;
  if (!o) return;

  // Pre-fill party if empty
  const partyEl = document.getElementById('ci-party');
  if (partyEl && !partyEl.value) partyEl.value = o.customer || '';

  _applyOrderToItem(i, o);
  const dd = document.getElementById('ci-item-dd-' + i);
  if (dd) dd.style.display = 'none';
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function renderInvoiceItemRows() {
  const container = document.getElementById('ci-items-table');
  if (!container) return;

  container.innerHTML = `
    <div style="display:grid;grid-template-columns:2fr 80px 90px 88px 24px;gap:6px;font-size:11px;font-weight:700;color:var(--muted);margin-bottom:4px;padding:0 2px">
      <div>Product / Description</div><div>Qty</div><div>Rate (₹)</div><div>Amount</div><div></div>
    </div>` +
    _ciItems.map((item, i) => {
      const linked = item.orderId
        ? `<div style="font-size:10px;color:#15803D;margin-top:3px;display:flex;align-items:center;gap:4px;white-space:nowrap">
             ✅ <strong>${item.orderId}</strong> · deducts + marks Delivered
             <button onclick="_ciItems[${i}].orderId=null;_ciItems[${i}].challanDc=null;renderInvoiceItemRows()" title="Unlink" style="background:none;border:none;cursor:pointer;color:#15803D;font-size:13px;line-height:1">×</button>
           </div>`
        : '';
      return `
    <div style="display:grid;grid-template-columns:2fr 80px 90px 88px 24px;gap:6px;margin-bottom:8px;align-items:start">
      <div style="position:relative">
        <input class="form-input" type="text" placeholder="Type or click to see this party's products…" value="${(item.desc || '').replace(/"/g,'&quot;')}"
          autocomplete="off" style="font-size:12px;padding:6px 8px;${item.orderId ? 'border-color:#86EFAC;background:#F0FDF4' : ''}"
          oninput="onInvoiceItemProductInput(${i}, this.value)" onfocus="onInvoiceItemProductFocus(${i})">
        <div id="ci-item-dd-${i}" class="ci-item-dd" style="display:none;position:absolute;top:100%;left:0;right:0;background:var(--white);border:1px solid var(--border);border-radius:8px;max-height:200px;overflow-y:auto;z-index:${200 - i};box-shadow:0 6px 20px rgba(0,0,0,0.15)"></div>
        ${linked}
      </div>
      <input class="form-input" type="number" placeholder="0" value="${item.qty !== '' ? item.qty : ''}"
        style="font-size:12px;padding:6px 8px" oninput="_ciItems[${i}].qty=+this.value||0;recalcInvoiceTotals()">
      <input class="form-input" type="number" placeholder="0.00" step="0.01" value="${item.rate !== '' ? item.rate : ''}"
        style="font-size:12px;padding:6px 8px" oninput="_ciItems[${i}].rate=+this.value||0;recalcInvoiceTotals()">
      <div style="font-size:12px;font-weight:700;padding:6px 0;text-align:right">₹${(+(item.qty||0) * +(item.rate||0)).toFixed(2)}</div>
      ${_ciItems.length > 1
        ? `<button onclick="removeInvoiceItem(${i})" style="background:none;border:none;cursor:pointer;font-size:18px;color:var(--danger);line-height:1;padding:4px 0">×</button>`
        : '<div></div>'}
    </div>`;
    }).join('');
}

function addInvoiceItemRow() {
  _ciItems.push({ desc: '', qty: '', rate: '', orderId: null, challanDc: null });
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function removeInvoiceItem(i) {
  _ciItems.splice(i, 1);
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function recalcInvoiceTotals() {
  const subtotal = _ciItems.reduce((s, item) => s + +(item.qty || 0) * +(item.rate || 0), 0);
  const total    = Math.round(subtotal);
  const roundOff = total - subtotal;
  const fmt2  = n => n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const subEl = document.getElementById('ci-subtotal');
  const roEl  = document.getElementById('ci-roundoff');
  const tot   = document.getElementById('ci-total');
  if (subEl) subEl.textContent = '₹' + fmt2(subtotal);
  if (roEl)  roEl.textContent  = (roundOff >= 0 ? '+ ₹' : '- ₹') + fmt2(Math.abs(roundOff));
  if (tot)   tot.textContent   = '₹' + fmt2(total);
}

function _buildInvoiceRecord() {
  const party   = (document.getElementById('ci-party')?.value || '').trim();
  const dateVal = document.getElementById('ci-date')?.value || new Date().toISOString().slice(0, 10);

  const items = _ciItems.filter(item => item.desc && +(item.qty || 0) > 0);

  if (!party)        { alert('Please enter party name.'); return null; }
  if (!items.length) { alert('Please add at least one item with a product name and qty > 0.'); return null; }

  const subtotal = items.reduce((s, i) => s + +(i.qty) * +(i.rate || 0), 0);
  // Rounded to the nearest rupee — standard practice so the payable amount
  // is a whole number; the odd paise show as a separate Round Off line
  // rather than getting silently absorbed or left as a fractional total.
  const total    = Math.round(subtotal);
  const roundOff = total - subtotal;

  // Primary orderId = first linked row (kept for backward-compat display in list/print)
  const firstLinked = items.find(i => i.orderId);

  return {
    id:        generateInvoiceId(),
    party,
    date:      dateVal,
    orderId:   firstLinked ? firstLinked.orderId : null,
    items:     items.map(i => ({ desc: i.desc, qty: +i.qty, rate: +(i.rate || 0), amount: +i.qty * +(i.rate || 0), orderId: i.orderId || null, challanDc: i.challanDc || null, svTs: i.svTs || null })),
    subtotal,
    gstPct:    0,
    gstAmt:    0,
    roundOff,
    total,
    createdAt: new Date().toISOString(),
  };
}

// Persist the built record — creating new or updating the one being edited.
// Returns the saved invoice, or null on validation failure.
function _persistInvoice() {
  const inv = _buildInvoiceRecord();
  if (!inv) return null;

  // Mutates inv.autoDeliveredOrders (order id + its status before this
  // invoice touched it) — must happen before the invoice itself is saved,
  // so that record is there for rollbackInvoice() to read back later.
  _markInvoicedOrdersDelivered(inv);

  if (_ciEditingId) {
    const idx = invoiceList.findIndex(x => x.id === _ciEditingId);
    if (idx >= 0) {
      inv.id = _ciEditingId;                       // keep the original number
      inv.createdAt = invoiceList[idx].createdAt;  // keep original timestamp
      invoiceList[idx] = inv;
    } else {
      invoiceList.unshift(inv);
    }
  } else {
    invoiceList.unshift(inv);
  }
  saveInvoiceList();
  _mirrorInvoice(inv);
  if (typeof logOrderEvent === 'function') {
    [...new Set((inv.items || []).map(i => i.orderId).filter(Boolean))]
      .forEach(oid => logOrderEvent(oid, 'Invoiced', `${inv.id} · ₹${inv.total.toLocaleString('en-IN')}`));
  }
  return inv;
}

// Push an invoice to its own Invoices sheet (readable columns)
function _mirrorInvoice(inv) {
  if (typeof mirrorToSheet !== 'function') return;
  const orderIds = [...new Set((inv.items || []).map(i => i.orderId).filter(Boolean))].join(', ');
  const itemsTxt = (inv.items || []).map(i => `${i.desc} x${i.qty} @${i.rate}`).join('; ');
  const qty      = (inv.items || []).reduce((s, i) => s + (i.qty || 0), 0);
  mirrorToSheet('saveInvoice', {
    id: inv.id, date: inv.date, party: inv.party, orderIds,
    items: itemsTxt, qty, total: inv.total, createdAt: inv.createdAt || '',
  });
}

// Any order linked from this invoice's items is considered fully billed → Delivered.
// Records each order's status just before the flip on inv.autoDeliveredOrders,
// so rollbackInvoice() can put it back exactly where it was instead of guessing.
function _markInvoicedOrdersDelivered(inv) {
  if (typeof orders === 'undefined') return;
  const orderIds = [...new Set((inv.items || []).map(i => i.orderId).filter(Boolean))];
  const autoDelivered = [];
  orderIds.forEach(oid => {
    const o = orders.find(x => x.id === oid);
    if (o && o.status !== 'Delivered' && o.status !== 'Cancelled') {
      autoDelivered.push({ orderId: oid, prevStatus: o.status });
      markOrderDelivered(o);
      if (typeof logOrderEvent === 'function') logOrderEvent(oid, 'Status Changed', `${autoDelivered[autoDelivered.length-1].prevStatus} → Delivered (auto — invoiced ${inv.id})`);
    }
  });
  if (autoDelivered.length) inv.autoDeliveredOrders = autoDelivered;
}

// Flip an order to Delivered — optimistic local update + push to the sheet.
function markOrderDelivered(o) {
  o.status = 'Delivered';
  if (typeof recordDeliveredOrder === 'function') recordDeliveredOrder(o);
  if (typeof recordDeliveryLead   === 'function') recordDeliveryLead(o);
  try {
    const d   = o.date ? new Date(o.date) : new Date();
    const fmt = `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`;
    const od  = o.orderDate ? new Date(o.orderDate) : d;
    const fod = `${String(od.getDate()).padStart(2,'0')}/${String(od.getMonth()+1).padStart(2,'0')}/${od.getFullYear()}`;
    fetch(APPS_SCRIPT_URL, {
      method: 'POST', mode: 'no-cors', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'update', rowIndex: o.rowIndex, id: o.id, customer: o.customer,
        product: o.product, size: o.size, ply: o.ply, colour: o.colour, weight: o.weight,
        qty: o.qty, rate: o.rate, date: fmt, orderDate: fod, status: 'Delivered',
        priority: o.priority, reelSize: o.reelSize, reservedKg: o.reservedKg || 0, remarks: '',
      }),
    }).catch(() => {});
  } catch (e) { /* non-fatal */ }
}

// The invoice form is a fixed overlay that no longer navigates away from
// wherever it was opened (Supervisor Log included) — so if that table is
// the page sitting underneath, it needs telling to re-render after a save,
// or its "already invoiced" checkmarks stay stale until the next unrelated
// refresh. Re-renders from data already in memory; never re-fetches.
function _refreshSvlogIfOpen() {
  if (document.getElementById('svlog-root') && typeof renderSupervisorLog === 'function') {
    renderSupervisorLog(false);
  }
}

function saveInvoiceOnly() {
  const inv = _persistInvoice();
  if (!inv) return;
  const wasEditing = !!_ciEditingId;
  closeCreateInvoice();
  renderInvoicingPage();
  renderUnratedChallanBanner();
  if (typeof renderOrders === 'function') renderOrders();
  if (typeof updateDashboardOrders === 'function') updateDashboardOrders();
  _refreshSvlogIfOpen();
  alert(`✅ ${inv.id} ${wasEditing ? 'updated' : 'saved'}!`);
}

function saveAndPrintInvoice() {
  const inv = _persistInvoice();
  if (!inv) return;
  closeCreateInvoice();
  renderInvoicingPage();
  renderUnratedChallanBanner();
  if (typeof renderOrders === 'function') renderOrders();
  if (typeof updateDashboardOrders === 'function') updateDashboardOrders();
  _refreshSvlogIfOpen();
  _populateInvoiceOverlay(inv);
}

// Re-open the create form pre-filled to edit an existing invoice
function editInvoice(invId) {
  const inv = invoiceList.find(i => i.id === invId);
  if (!inv) return;
  const overlay = document.getElementById('create-invoice-overlay');
  if (!overlay) return;

  _ciEditingId = invId;
  _ciItems = (inv.items || []).map(i => ({ desc: i.desc, qty: i.qty, rate: i.rate, orderId: i.orderId || null, challanDc: i.challanDc || null, svTs: i.svTs || null }));
  if (!_ciItems.length) _ciItems = [{ desc: '', qty: '', rate: '', orderId: null, challanDc: null }];

  const titleEl = document.querySelector('#create-invoice-overlay .popup-title');
  if (titleEl) titleEl.textContent = `✏️ Edit Invoice ${inv.id}`;

  const partyEl = document.getElementById('ci-party');
  if (partyEl) partyEl.value = inv.party || '';
  const dateEl = document.getElementById('ci-date');
  if (dateEl) dateEl.value = inv.date || new Date().toISOString().slice(0, 10);

  const dl = document.getElementById('ci-party-list');
  if (dl && typeof CLIENTS !== 'undefined') dl.innerHTML = CLIENTS.map(c => `<option value="${c.name}">`).join('');

  overlay.style.display = 'flex';
  renderInvoiceItemRows();
  recalcInvoiceTotals();
}

function _populateInvoiceOverlay(inv) {
  const ordObj = inv.orderId && typeof orders !== 'undefined' ? orders.find(o => o.id === inv.orderId) : null;
  const client = inv.party && typeof CLIENTS !== 'undefined'
    ? (CLIENTS.find(c => c.name.toLowerCase() === inv.party.toLowerCase()) || {})
    : {};
  const fmt2   = n => n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const dateStr = (() => {
    try { return new Date(inv.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }); }
    catch { return inv.date; }
  })();

  document.getElementById('inv-number').textContent          = inv.id;
  document.getElementById('inv-date').textContent            = dateStr;
  document.getElementById('inv-order-id').textContent        = inv.orderId || '—';
  document.getElementById('inv-delivery-date').textContent   = ordObj ? formatDate(ordObj.date) : '—';
  document.getElementById('inv-customer-name').textContent   = inv.party;
  document.getElementById('inv-customer-contact').textContent = client.contact || '';
  document.getElementById('inv-customer-city').textContent   = client.city    || '';
  document.getElementById('inv-customer-phone').textContent  = client.phone   ? '📞 ' + client.phone : '';

  document.getElementById('inv-items').innerHTML = inv.items.map(item => `
    <tr style="border-bottom:1px solid #e5e7eb">
      <td style="padding:12px;font-size:13px">${item.desc}</td>
      <td style="padding:12px;text-align:center;font-size:13px">${item.qty.toLocaleString('en-IN')} pcs</td>
      <td style="padding:12px;text-align:right;font-size:13px">₹${item.rate.toFixed(2)}</td>
      <td style="padding:12px;text-align:right;font-size:13px;font-weight:600">₹${fmt2(item.amount)}</td>
    </tr>`).join('');

  const hasGst     = (inv.gstPct || 0) > 0;
  const roundOff   = inv.roundOff || 0;
  const hasRoundOff = Math.abs(roundOff) >= 0.005;
  document.getElementById('inv-subtotal').textContent = '₹' + fmt2(inv.subtotal);
  const gstRow      = document.getElementById('inv-gst-row');
  const roundRow    = document.getElementById('inv-roundoff-row');
  const subtotalRow = document.getElementById('inv-subtotal-row');
  const docTitle    = document.getElementById('inv-doc-title');
  if (gstRow)      gstRow.style.display      = hasGst ? '' : 'none';
  if (roundRow)    roundRow.style.display    = hasRoundOff ? '' : 'none';
  // Subtotal is only worth a separate line when it actually differs from
  // the final total (GST added, or rounded off) — otherwise it's the same
  // number twice.
  if (subtotalRow) subtotalRow.style.display = (hasGst || hasRoundOff) ? '' : 'none';
  if (docTitle)    docTitle.textContent      = hasGst ? 'TAX INVOICE' : 'INVOICE';
  if (hasGst) {
    const gstLabelEl = document.getElementById('inv-gst-label');
    if (gstLabelEl) gstLabelEl.textContent = `GST @ ${inv.gstPct}%`;
    document.getElementById('inv-gst').textContent = '₹' + fmt2(inv.gstAmt);
  }
  if (hasRoundOff) {
    document.getElementById('inv-roundoff').textContent = (roundOff > 0 ? '+ ₹' : '- ₹') + fmt2(Math.abs(roundOff));
  }
  document.getElementById('inv-total').textContent = '₹' + fmt2(inv.total);
  document.getElementById('inv-amount-words').textContent = amountToWords(Math.round(inv.total));

  document.getElementById('invoice-overlay').style.display = 'flex';
}

function reprintInvoice(invId) {
  const inv = invoiceList.find(i => i.id === invId);
  if (inv) _populateInvoiceOverlay(inv);
}

// Deleting an invoice that auto-marked an order Delivered also rolls that
// order back to whatever status it was in right before — otherwise the
// order would be left showing Delivered with no invoice to justify it.
// autoDeliveredOrders (set in _markInvoicedOrdersDelivered) is only
// present on invoices created after that tracking was added; older
// invoices just delete with no order-status side effect, same as before.
function deleteInvoice(invId) {
  const inv = invoiceList.find(i => i.id === invId);
  const revertList = inv?.autoDeliveredOrders || [];
  const confirmMsg = revertList.length
    ? `Roll back invoice ${invId}? This deletes it and reverts ${revertList.length} order(s) it marked Delivered back to their previous status.`
    : `Delete invoice ${invId}? This cannot be undone.`;
  if (!confirm(confirmMsg)) return;

  revertList.forEach(({ orderId, prevStatus }) => {
    const o = typeof orders !== 'undefined' ? orders.find(x => x.id === orderId) : null;
    if (o && o.status === 'Delivered') {
      o.status = prevStatus || 'New';
      if (typeof _pushOrderUpdate === 'function') _pushOrderUpdate(o);
      if (typeof logOrderEvent === 'function') logOrderEvent(orderId, 'Rolled Back', `Invoice ${invId} rolled back — status reverted to ${o.status}`);
    }
  });

  invoiceList = invoiceList.filter(inv => inv.id !== invId);
  saveInvoiceList();
  if (typeof mirrorToSheet === 'function') mirrorToSheet('deleteInvoice', { id: invId });
  renderInvoicingPage();
  renderUnratedChallanBanner();
  if (typeof renderOrders === 'function') renderOrders();
  if (typeof updateDashboardOrders === 'function') updateDashboardOrders();
  _refreshSvlogIfOpen();
}

function closeInvoice() {
  document.getElementById('invoice-overlay').style.display = 'none';
}

// Close per-row product dropdowns on outside click
document.addEventListener('click', e => {
  const table = document.getElementById('ci-items-table');
  if (table && !table.contains(e.target)) _hideAllItemDropdowns();
});

// ── Print Invoice (new window) ──
function printInvoice() {
  const content = document.getElementById('invoice-printable').innerHTML;
  const win = window.open('', '_blank');
  win.document.write(`
    <!DOCTYPE html><html><head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: 'Inter', Arial, sans-serif; padding: 40px; font-size: 13px; color: #111; }
      table { width: 100%; border-collapse: collapse; }
      th, td { border: 1px solid #e5e7eb; }
    </style>
    </head><body>${content}</body></html>
  `);
  win.document.close();
  win.focus();
  win.print();
}

// ── Month filter — defaults to the current month (or the most recent month
// that actually has invoices, if this one doesn't) the first time the page
// renders; stays wherever the user leaves it after that. ──
let _invMonthFilter = null;

function _invMonthKey(dateStr)  { return (dateStr || '').slice(0, 7); } // 'YYYY-MM'
function _invMonthLabel(key) {
  const [y, m] = key.split('-').map(Number);
  return new Date(y, m - 1, 1).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
}

function setInvoiceMonthFilter(key) {
  _invMonthFilter = key;
  renderInvoicingPage();
}

// ── Invoicing Page ──
function renderInvoicingPage() {
  const el = document.getElementById('invoicing-page-content');
  if (!el) return;

  const fmt2 = n => n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const allMonths = [...new Set(invoiceList.map(inv => _invMonthKey(inv.date)).filter(Boolean))].sort().reverse();
  if (_invMonthFilter === null) {
    const curMonth = todayStr.slice(0, 7);
    _invMonthFilter = allMonths.includes(curMonth) ? curMonth : (allMonths[0] || 'all');
  }
  const filtered = _invMonthFilter === 'all' ? invoiceList : invoiceList.filter(inv => _invMonthKey(inv.date) === _invMonthFilter);

  const totalInvoiced = filtered.reduce((s, inv) => s + inv.total, 0);
  const unbilled = _unbilledChallans();

  const monthSelect = `
    <select class="form-select" style="font-size:13px;width:auto;padding:8px 10px" onchange="setInvoiceMonthFilter(this.value)">
      <option value="all" ${_invMonthFilter === 'all' ? 'selected' : ''}>All Months</option>
      ${allMonths.map(m => `<option value="${m}" ${m === _invMonthFilter ? 'selected' : ''}>${_invMonthLabel(m)}</option>`).join('')}
    </select>`;

  el.innerHTML = `
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;flex-wrap:wrap;gap:8px">
      <div style="display:flex;gap:12px;flex-wrap:wrap;align-items:center">
        ${monthSelect}
        <div class="stat-card good" style="padding:10px 16px;min-width:140px">
          <div class="stat-label">Total Invoiced${_invMonthFilter !== 'all' ? ' — ' + _invMonthLabel(_invMonthFilter) : ''}</div>
          <div class="stat-value" style="color:var(--success);font-size:18px">₹${fmt2(totalInvoiced)}</div>
        </div>
        <div class="stat-card info" style="padding:10px 16px;min-width:100px">
          <div class="stat-label">Invoices</div>
          <div class="stat-value">${filtered.length}</div>
        </div>
      </div>
      <button class="btn-primary" onclick="openCreateInvoiceForm(null)" style="font-size:13px">+ New Invoice</button>
    </div>

    ${unbilled.length ? `
    <div class="card" style="margin-bottom:16px;border-color:#FBBF24">
      <div class="card-body" style="padding:12px 16px">
        <div style="font-size:12px;font-weight:700;color:#B45309;margin-bottom:6px">⚠️ ${unbilled.length} delivery challan${unbilled.length > 1 ? 's' : ''} not yet invoiced — no rate on file</div>
        <div style="font-size:11px;color:var(--muted);margin-bottom:8px">These dispatched automatically but have no rate to bill from. Add a rate on the order (or the product master) and they'll invoice on the next dispatch refresh — or invoice them manually now.</div>
        <div style="display:flex;flex-direction:column;gap:4px">
          ${unbilled.map(c => `<div style="font-size:12px;display:flex;gap:10px;flex-wrap:wrap">
            <span style="font-family:monospace;color:var(--navy);font-weight:700">${c.dcNum}</span>
            <span>${c.customer}</span>
            <span style="color:var(--muted)">${c.product || c.size || '—'}</span>
            <span style="color:var(--muted)">${(c.qty || 0).toLocaleString('en-IN')} pcs</span>
            <button class="btn-secondary" style="font-size:10px;padding:2px 8px;margin-left:auto" onclick="resolveChallanInvoice('${c.dcNum}','${c.orderId}')">+ Invoice manually</button>
          </div>`).join('')}
        </div>
      </div>
    </div>` : ''}

    ${filtered.length === 0
      ? `<div class="empty-state">${invoiceList.length === 0 ? 'No invoices yet. Click "+ New Invoice" to create one.' : `No invoices in ${_invMonthFilter === 'all' ? 'range' : _invMonthLabel(_invMonthFilter)}.`}</div>`
      : (() => {
          const invGridCols = '85px 85px 1fr 1fr 85px 55px 70px 90px 120px';
          return `<div class="card">
          <div class="card-body" style="padding:0">
            <div class="orders-table">
              <div class="table-header" style="grid-template-columns:${invGridCols};gap:8px">
                <div>Invoice #</div><div>Date</div><div>Party</div><div>Product</div><div>Order</div><div>Qty</div><div>Rate</div><div>Total</div><div>Actions</div>
              </div>
              ${(() => {
                const sorted = filtered.slice().sort(_invByDateThenParty);
                // Per-day revenue total — shown once, on the day's first row
                const dayTotals = {};
                sorted.forEach(inv => {
                  const d = inv.date || '';
                  if (!dayTotals[d]) dayTotals[d] = { total: 0, count: 0 };
                  dayTotals[d].total += (inv.total || 0);
                  dayTotals[d].count++;
                });
                let prevDate = null;
                return sorted.map(inv => {
                const qty = (inv.items || []).reduce((s, i) => s + (i.qty || 0), 0);
                const dateDisp = (() => { try { return new Date(inv.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }); } catch { return inv.date; } })();
                const orderIds = [...new Set((inv.items || []).map(i => i.orderId).filter(Boolean))];
                const orderLbl = orderIds.length ? orderIds.join(', ') : (inv.orderId || '—');
                const products = [...new Set((inv.items || []).map(i => (i.desc || '').split(' · ')[0]).filter(Boolean))];
                const productLbl = products.length ? products.join(', ') : '—';
                const rates = [...new Set((inv.items || []).map(i => +i.rate || 0))];
                const rateLbl = rates.length === 1 ? '₹' + fmt2(rates[0]) : (rates.length > 1 ? 'multi' : '—');
                // New date group — a visible break per day; within a day, parties
                // are already clustered by the sort itself
                const newGroup = inv.date !== prevDate;
                prevDate = inv.date;
                const dayHeader = newGroup ? (() => {
                  const dt = dayTotals[inv.date || ''];
                  return `<div style="display:flex;justify-content:space-between;align-items:center;padding:6px 16px;background:var(--bg);font-size:11px;font-weight:700;color:var(--muted)">
                    <span>${dateDisp}</span>
                    <span>${dt.count} invoice${dt.count > 1 ? 's' : ''} · <span style="color:var(--navy)">₹${fmt2(dt.total)}</span> that day</span>
                  </div>`;
                })() : '';
                return dayHeader + `
                <div class="table-row" style="grid-template-columns:${invGridCols};gap:8px;cursor:pointer;${newGroup ? 'border-top:2px solid var(--navy)' : ''}" onclick="editInvoice('${inv.id}')" title="Click to edit">
                  <div style="font-family:monospace;font-size:12px;color:var(--navy);font-weight:700">${inv.id}${inv.autoGenerated ? ` <span style="font-family:inherit;font-size:9px;font-weight:700;color:var(--success,#27AE60);background:#F0FDF4;padding:1px 5px;border-radius:3px;vertical-align:middle" title="Auto-generated from a Delivery Challan">AUTO</span>` : ''}</div>
                  <div style="font-size:12px">${dateDisp}</div>
                  <div style="font-size:12px;font-weight:600">${inv.party}</div>
                  <div style="font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="${productLbl}">${productLbl}</div>
                  <div style="font-size:11px;font-family:monospace;color:var(--muted)">${orderLbl}</div>
                  <div style="font-size:12px">${qty.toLocaleString('en-IN')}</div>
                  <div style="font-size:12px">${rateLbl}</div>
                  <div style="font-size:12px;font-weight:700;color:var(--navy)">₹${fmt2(inv.total)}</div>
                  <div style="display:flex;gap:5px;align-items:center" onclick="event.stopPropagation()">
                    <button class="btn-secondary" style="font-size:10px;padding:3px 7px" onclick="editInvoice('${inv.id}')" title="Edit">✏️</button>
                    <button class="btn-secondary" style="font-size:10px;padding:3px 7px" onclick="reprintInvoice('${inv.id}')" title="Print">🖨</button>
                    <button style="background:none;border:none;cursor:pointer;font-size:15px;color:var(--danger)" onclick="deleteInvoice('${inv.id}')" title="${inv.autoDeliveredOrders?.length ? 'Roll back — deletes this invoice and reverts the order(s) it marked Delivered' : 'Delete'}">${inv.autoDeliveredOrders?.length ? '↩️' : '🗑'}</button>
                  </div>
                </div>`;
              }).join('');
              })()}
            </div>
          </div>
        </div>`;
        })()
    }
  `;
}

// ── Number to Words (Indian format) ──
function amountToWords(amount) {
  if (amount === null || amount === undefined || isNaN(amount)) return '';
  if (amount === 0) return 'Rupees Zero Only';
  const ones = ['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine',
    'Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'];
  const tens = ['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];
  function convert(n) {
    if (n < 20) return ones[n];
    if (n < 100) return tens[Math.floor(n/10)] + (n%10 ? ' ' + ones[n%10] : '');
    if (n < 1000) return ones[Math.floor(n/100)] + ' Hundred' + (n%100 ? ' ' + convert(n%100) : '');
    if (n < 100000) return convert(Math.floor(n/1000)) + ' Thousand' + (n%1000 ? ' ' + convert(n%1000) : '');
    if (n < 10000000) return convert(Math.floor(n/100000)) + ' Lakh' + (n%100000 ? ' ' + convert(n%100000) : '');
    return convert(Math.floor(n/10000000)) + ' Crore' + (n%10000000 ? ' ' + convert(n%10000000) : '');
  }
  return 'Rupees ' + convert(amount) + ' Only';
}
